#!/usr/bin/env python2

"""
find all public objects in a given s3 bucket
return the key of that object
"""

import argparse
import boto3


parser = argparse.ArgumentParser()
parser.add_argument("bucket", help="s3 bucket to check", type=str)
args = parser.parse_args()

s3_client = boto3.client('s3')

# get objects from bucket
objects = s3_client.list_objects_v2(
    Bucket=args.bucket
    )

obj_keys = []
for i in objects['Contents']:
    obj_keys.append(i['Key'])

print obj_keys
# get acl of objects
# find pub method/key in acl
"""
for key in obj_keys:
    obj_acl = s3_client.get_object_act(Bucket=bucket,Key=key)
    for acl in obj_acl.
    if "AllUsers" in str(obj_acl.values())
        print i
"""
# check if public
