#!/usr/bin/env python2

"""
find all public objects in a given s3 bucket
return the key of that object
"""

import argparse
import boto3


parser = argparse.ArgumentParser()
parser.add_argument("bucket", help="s3 bucket to check", type=str)
args = parser.parse_args()

s3_client = boto3.client('s3')

# create iterator
paginator = s3_client.get_paginator('list_objects')
page_iterator = paginator.paginate(Bucket=args.bucket)

obj_keys = [obj['Key'] for page in page_iterator for obj in page['Contents']]

# get acl of objects and check for "AllUsers" in acl
for key in obj_keys:
    obj_acl = s3_client.get_object_acl(Bucket=args.bucket,Key=key)
    if "AllUsers" in str(obj_acl.values()):
        print key
